version: '2'
services:
  jenkins:
    image: dipayanr/droy-jenkins-image:latest
    container_name : jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
#disabled#  postgres:
#disabled#    image: postgres:9.6
#disabled#    networks:
#disabled#      - jenkins
#disabled#    environment:
#disabled#      POSTGRES_USER: sonar
#disabled#      POSTGRES_PASSWORD: sonarpasswd
#disabled#    volumes:
#disabled#      - /var/postgres-data:/var/lib/postgresql/data
#disabled#  sonarqube:
#disabled#    image: sonarqube:lts
#disabled#    ports:
#disabled#      - "9000:9000"
#disabled#      - "9092:9092"
#disabled#    networks:
#disabled#      - jenkins
#disabled#    environment:
#disabled#      SONARQUBE_JDBC_USERNAME: sonar
#disabled#      SONARQUBE_JDBC_PASSWORD: sonarpasswd
#disabled#      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
#disabled#    depends_on: 
#disabled#      - postgres
#disabled#
networks:
  jenkins:
